### ISSUE TITLE
dependencies ubuntu 19.10

### ISSUE THREAD

**Issue by gsouf** [edgedb/edgedb-pkg#3]
Hello, I cannot install on ubuntu 19.10.

```
sudo apt-get install edgedb-1-alpha2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 edgedb-1-alpha2 : Depends: libicu60 (>= 60.2-3ubuntu3) but it is not installable
                   Depends: libreadline7 (>= 7.0~beta) but it is not installable
E: Unable to correct problems, you have held broken packages.
````

`libicu63` and `libreadline8` are installed on my machine. I think it's just a matter of allowing newest version of these vendors.

Thanks

**Comment by elprans** [comment]
The packages are distribution version-specific.  At the moment we only support the LTS releases of Ubuntu: 16.04 and 18.04, as well as Stretch and Buster releases of Debian.  For other versions a Docker image is available.

You can also try building the packages yourself.  For that you need to add `ubuntu-eoan` to `SUPPORTED_TARGETS` in the Makefile and then:

```sh
$ mkdir integration/linux/build/ubuntu-eoan
$ make TARGET=ubuntu-eoan PKG_VERSION=1.0a2 \
    PKG_VERSION_SLOT=1-alpha2 SRC_REF=releases/1.0a2 build
```

Once that completes, you will find the packages in `/tmp/artifacts`, which you should be able to install on your system with:

```sh
$ apt install /tmp/artifacts/edgedb-common_*_amd64.deb \
               /tmp/artifacts/edgedb-1-alpha2_*_amd64.deb
```

**Comment by gsouf** [comment]
@elprans had to enable it in the make file too. Getting some more errors. I'm giving up for now as the docker way works well! 

Thanks
